---
- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Start Apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: Install MySQL
  yum:
    name: mariadb105-server
    state: present

- name: Start MySQL
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Install Python3
  yum:
    name: python3
    state: present

- name: Install pip
  yum:
    name: python3-pip
    state: present

- name: Install Flask
  pip:
    name: flask
    executable: pip3

- name: Deploy Python application
  template:
    src: app.py.j2
    dest: /home/ec2-user/app.py

- name: Run Python Flask application
  shell: nohup python3 /home/ec2-user/app.py > /dev/null 2>&1 &
  async: 10
  poll: 0
